// Copyright © Klarälvdalens Datakonsult AB, a KDAB Group company , info@kdab.com, author Robin Cramer <robin.cramer@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

struct ShapeProp {
    corner-shape: corner-shape
}

global G {
    in-out property <corner-shape> a: CornerShape.notch;
    in-out property <ShapeProp> p: { corner-shape: CornerShape.scoop };
}


export component TestCase inherits Window {
    in-out property <corner-shape> corner-shape: bevel;

    out property <bool> test: corner-shape == CornerShape.bevel && corner-shape != CornerShape.round && G.p.corner-shape == CornerShape.scoop;
}

/*
```rust
let instance = TestCase::new().unwrap();
assert!(instance.get_test());
```

```cpp
auto handle = TestCase::create();
const TestCase &instance = *handle;
assert(instance.get_test());
```
*/

